import { describe, expect, it } from "vitest";
import { mkdtemp, readFile } from "node:fs/promises";
import { tmpdir } from "node:os";
import { FakeProvider } from "../../src/server/providers/fake-provider.js";
import { runTwoPass } from "../../src/server/jobs/job-runner.js";
describe("two-pass pipeline",()=>{
  it("persists drafts before edits in chapter order",async()=>{const root=await mkdtemp(`${tmpdir()}/book-translator-`),provider=new FakeProvider(),profile={name:"fake",endpoint:"local",model:"fake"};await runTwoPass([{id:"batch-1",documentId:"chapter-1",segments:[{id:"chapter-1:0",text:"Hello",sourceHash:"",locator:[],leading:"",trailing:""}]}],provider,{root,translationProfile:profile,editingProfile:profile});expect(provider.requests.map(x=>x.mode)).toEqual(["translation","editing"]);expect((await readFile(`${root}/drafts.ndjson`,`utf8`)).length).toBeGreaterThan(0);});
  it("reuses only checkpoints produced from the same inputs and provider profile",async()=>{const root=await mkdtemp(`${tmpdir()}/book-resume-`),provider=new FakeProvider(),profile={name:"fake",endpoint:"local",model:"v1"},batches=[{id:"chapter-1-batch-1",documentId:"chapter-1",segments:[{id:"chapter-1:0",text:"Hello",sourceHash:"",locator:[],leading:"",trailing:""}]}];await runTwoPass(batches,provider,{root,translationProfile:profile,editingProfile:profile,instructions:"Keep names"});await runTwoPass(batches,provider,{root,translationProfile:profile,editingProfile:profile,instructions:"Keep names"});expect(provider.requests).toHaveLength(2);const changed={...profile,model:"v2"};await runTwoPass(batches,provider,{root,translationProfile:changed,editingProfile:changed,instructions:"Keep names"});expect(provider.requests).toHaveLength(4);});
  it("reuses content checkpoints after batch identifiers change",async()=>{const root=await mkdtemp(`${tmpdir()}/book-checkpoint-migration-`),provider=new FakeProvider(),profile={name:"fake",endpoint:"local",model:"v1"},segment={id:"chapter-1:0",text:"Hello",sourceHash:"",locator:[],leading:"",trailing:""};await runTwoPass([{id:"batch-1",documentId:"chapter-1",segments:[segment]}],provider,{root,translationProfile:profile,editingProfile:profile});const result=await runTwoPass([{id:"chapter-1-batch-1",documentId:"chapter-1",segments:[segment]}],provider,{root,translationProfile:profile,editingProfile:profile});expect(provider.requests).toHaveLength(2);expect(result.edits.get("chapter-1-batch-1")?.[0]?.text).toBe("[translated] Hello");});
});
