import { Router } from "express";
import { mkdir, writeFile } from "node:fs/promises";
import { createReadStream } from "node:fs";
import { join } from "node:path";
import { assertLanguagePair } from "../../shared/languages.js";
import { newJobId, jobRoot } from "../storage/job-paths.js";
import { type JobRepository } from "../storage/job-repository.js";
import { toJobView } from "../domain/job.js";
import { problemResponse } from "./problem.js";
export function jobsRouter(repo:JobRepository){const router=Router();router.get("/",async(_req,res)=>res.json((await repo.list()).map(toJobView)));router.post("/",async(req,res)=>{try{const {title="Untitled book",sourceLanguage="en",targetLanguage}=req.body as Record<string,string>;if(!targetLanguage)throw new Error("targetLanguage is required");assertLanguagePair(sourceLanguage as any,targetLanguage as any);const id=newJobId(),now=new Date().toISOString();const job={version:1 as const,id,title,sourceLanguage,targetLanguage,status:"created",stage:"import",progress:{translated:0,edited:0,total:0,failed:0},createdAt:now,updatedAt:now,warnings:0,documents:[],instructions:"",glossary:[]};await repo.save(job);res.status(201).json(toJobView(job));}catch(e){problemResponse(res,e,req);}});router.get("/:id",async(req,res)=>{try{res.json(toJobView(await repo.get(req.params.id)));}catch(e){problemResponse(res,e,req);}});router.put("/:id/config",async(req,res)=>{try{const job=await repo.get(req.params.id),body=req.body as any;const next={...job,sourceLanguage:body.sourceLanguage??job.sourceLanguage,targetLanguage:body.targetLanguage??job.targetLanguage,instructions:body.instructions??job.instructions,glossary:body.glossary??job.glossary,updatedAt:new Date().toISOString()};assertLanguagePair(next.sourceLanguage as any,next.targetLanguage as any);await repo.save(next);res.json(toJobView(next));}catch(e){problemResponse(res,e,req);}});router.post("/:id/start",async(req,res)=>{try{const job=await repo.get(req.params.id),next={...job,status:"running",stage:"translation",updatedAt:new Date().toISOString()};await repo.save(next);res.status(202).json(toJobView(next));}catch(e){problemResponse(res,e,req);}});router.post("/:id/names/analyze",async(req,res)=>{try{const job=await repo.get(req.params.id),next={...job,status:"analyzing",stage:"analysis",updatedAt:new Date().toISOString()};await repo.save(next);res.status(202).json(toJobView(next));}catch(e){problemResponse(res,e,req);}});router.get("/:id/download",async(req,res)=>{try{const root=jobRoot(repo.dataDir,req.params.id);res.type("application/epub+zip").send(createReadStream(join(root,"output.epub")));}catch(e){problemResponse(res,e,req);}});router.delete("/:id",async(req,res)=>{try{await repo.remove(req.params.id);res.status(204).end();}catch(e){problemResponse(res,e,req);}});router.put("/:id/source",async(req,res)=>{try{const job=await repo.get(req.params.id);const root=jobRoot(repo.dataDir,job.id);await mkdir(root,{recursive:true});const buffer=Buffer.isBuffer(req.body)?req.body:Buffer.from(req.body);if(buffer.length>100*1024*1024)throw new Error("Upload exceeds configured limit");await writeFile(join(root,"source.epub"),buffer);res.status(204).end();}catch(e){problemResponse(res,e,req);}});return router;}
